export type Place = {
  id: string;
  name: string;
  country: string;
  state: string;
  city: string;
  street: string;
  num_place: number;
  complement: null;
  description: string;
  category_id: string;
  latitude: number;
  longitude: number;
  approved: boolean;
  approved_by: string;
  created_by: string;
  created_at: Date;
  updated_at: Date;
  images: Array<string>;
  likes: number;
  comments: number;
};
