import { cookies } from 'next/headers';

import { ThemeProvider } from '@/components/ThemeProvider';
import { Toaster } from '@/components/ui/Toaster';

import { constants } from '../utils/constants';
import { feedbackMessage } from '../utils/feedbackMessage';
import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

async function getTheme() {
  const cookieStore = await cookies();
  const themeFromCookie = cookieStore.get(constants.themeKey);
  return themeFromCookie?.value ?? 'dark';
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const theme = await getTheme();

  const message = await feedbackMessage.getFeedbackMessage();

  return (
    <html lang="en" className={theme} style={{ colorScheme: theme }}>
      <body className="h-screen xl:!px-40 scrollbar bg-gradient-to-b from-background to-background/90 dark:from-background dark:to-background/95">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
          storageKey={constants.themeKey}
        >
          <Toaster message={message} position="top-center" />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
