import { ThemeProvider } from "@/contexts/ThemeProvider";
import { NextUIProvider } from "@nextui-org/react";
import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className='h-full dark:bg-zinc-800'>
        <ThemeProvider>
          <NextUIProvider>
            {children}
          </NextUIProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
