import type { Metadata } from 'next';
import { cookies } from 'next/headers';

import { ThemeProvider } from '@/components/ThemeProvider';

import { constants } from '../utils/constants';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

function getTheme() {
  const cookieStore = cookies();
  const themeFromCookie = cookieStore.get(constants.themeKey);
  return themeFromCookie?.value ?? 'system';
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const theme = getTheme();

  return (
    <html lang="en" className={theme} style={{ colorScheme: theme }}>
      <body className="h-full text-slate-800 dark:text-white">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
