import { NextUIProvider } from '@nextui-org/react';
import type { Metadata } from 'next';

import { ThemeProvider } from '@/src/contexts/ThemeProvider';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className="h-full bg-slate-100 dark:bg-zinc-950">
        <ThemeProvider>
          <NextUIProvider>{children}</NextUIProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
