-- Up Migration
CREATE SCHEMA IF NOT EXISTS public;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TYPE ROLES AS ENUM ('ADMIN', 'USER');

CREATE TABLE users (
  id UUID DEFAULT uuid_generate_v4() CONSTRAINT users_pkey PRIMARY KEY,
  email VARCHAR(100) UNIQUE NOT NULL,
  name VARCHAR(255) NOT NULL,
  user_name VARCHAR(50) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  avatar_url VARCHAR(255),
  user_role ROLES DEFAULT('USER'),
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC')
);

CREATE TABLE reset_password_tokens (
  id UUID DEFAULT uuid_generate_v4() CONSTRAINT reset_password_tokens_pkey PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES users(id),
  reset_token VARCHAR(255) NOT NULL,
  used BOOLEAN DEFAULT FALSE,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC')
);

-- Down Migration
DROP TABLE IF EXISTS reset_password_tokens;
DROP TABLE IF EXISTS users;
DROP TYPE IF EXISTS ROLES;
DROP EXTENSION IF EXISTS "uuid-ossp";
