INSERT INTO places
  (
    name,
    country,
    street,
    city,
    state,
    num_place,
    complement,
    description,
    category_id,
    latitude,
    longitude,
    status,
    reviewed_by,
    created_by
  )
VALUES
  (
    'Churrascaria Espeto de Ouro',
    'Brasil',
    'Av. Nossa Senhora da Penha',
    'Vitória',
    'ES',
    1234,
    NULL,
    'Deliciosa churrascaria com variedade de comidas.',
    (SELECT id FROM categories WHERE name = 'restaurantes'),
    -20.3155,
    -40.3128,
    'APPROVED',
    (SELECT id FROM users WHERE user_role = 'ADMIN' LIMIT 1),
    (SELECT id FROM users WHERE user_role = 'ADMIN' LIMIT 1)
  ),
  (
    'Café Bamboo',
    'Brasil',
    'R. do Lazer',
    'Vitória',
    'ES',
    404,
    'Em frente a padaria',
    'Um café incrivel que oferece vários sabores inexplicáveis',
    (SELECT id FROM categories WHERE name = 'restaurantes'),
    -20.3155,
    -40.2969,
    'APPROVED',
    (SELECT id FROM users WHERE user_role = 'ADMIN' LIMIT 1),
    (SELECT id FROM USERS WHERE user_role = 'USER' LIMIT 1)
  ),
  (
    'Bar do Gerson',
    'Brasil',
    'Av. Hugo Musso',
    'Vila Velha',
    'ES',
    505,
    NULL,
    'Bar muito conhecido por seu ambiente agradável e bebidas geladas',
    (SELECT id FROM categories WHERE name = 'restaurantes'),
    -20.3274,
    -40.2922,
    'REJECTED',
    (SELECT id FROM users WHERE user_role = 'ADMIN' LIMIT 1),
    (SELECT id FROM users WHERE user_role = 'USER' LIMIT 1)
  ),
  (
    'Pizzaria do Zé',
    'Brasil',
    'Av. Jerônimo Monteiro',
    'Rio de Janeiro',
    'RJ',
    1234,
    NULL,
    'Pizzaria com variedade de sabores e promoções',
    (SELECT id FROM categories WHERE name = 'restaurantes'),
    -20.3155,
    -40.3128,
    'PENDING',
    NULL,
    (SELECT id FROM users WHERE user_role = 'USER' LIMIT 1)
  ),
  (
    'Pizzaria Sabor & Arte',
    'Brasil',
    'Rua das Flores, 123',
    'São Paulo',
    'SP',
    5678,
    NULL,
    'Pizzaria tradicional com sabores artesanais.',
    (SELECT id FROM categories WHERE name = 'restaurantes'),
    -23.5505,
    -46.6333,
    'APPROVED',
    (SELECT id FROM users WHERE user_role = 'ADMIN' LIMIT 1),
    (SELECT id FROM users WHERE user_role = 'ADMIN' LIMIT 1)
),
(
    'Bar do João',
    'Brasil',
    'Av. Atlântica, 456',
    'Rio de Janeiro',
    'RJ',
    7890,
    NULL,
    'Bar aconchegante com drinks exclusivos.',
    (SELECT id FROM categories WHERE name = 'bares'),
    -22.9068,
    -43.1729,
    'APPROVED',
    (SELECT id FROM users WHERE user_role = 'ADMIN' LIMIT 1),
    (SELECT id FROM users WHERE user_role = 'ADMIN' LIMIT 1)
),
(
    'Cafeteria Aroma & Sabor',
    'Brasil',
    'Rua dos Ipês, 789',
    'Belo Horizonte',
    'MG',
    4567,
    NULL,
    'Cafeteria com grãos especiais e ambiente aconchegante.',
    (SELECT id FROM categories WHERE name = 'restaurantes'),
    -19.9167,
    -43.9345,
    'APPROVED',
    (SELECT id FROM users WHERE user_role = 'ADMIN' LIMIT 1),
    (SELECT id FROM users WHERE user_role = 'ADMIN' LIMIT 1)
),
(
    'Restaurante Comida Mineira',
    'Brasil',
    'Rua das Palmeiras, 321',
    'Belo Horizonte',
    'MG',
    1011,
    NULL,
    'Pratos típicos da culinária mineira.',
    (SELECT id FROM categories WHERE name = 'restaurantes'),
    -19.9123,
    -43.9402,
    'APPROVED',
    (SELECT id FROM users WHERE user_role = 'ADMIN' LIMIT 1),
    (SELECT id FROM users WHERE user_role = 'ADMIN' LIMIT 1)
),
(
    'Hamburgueria Black Beef',
    'Brasil',
    'Av. Paulista, 654',
    'São Paulo',
    'SP',
    9876,
    NULL,
    'Hamburgueria artesanal com ingredientes selecionados.',
    (SELECT id FROM categories WHERE name = 'restaurantes'),
    -23.5645,
    -46.6525,
    'APPROVED',
    (SELECT id FROM users WHERE user_role = 'ADMIN' LIMIT 1),
    (SELECT id FROM users WHERE user_role = 'ADMIN' LIMIT 1)
),
(
    'Sorveteria Gelato & Cia',
    'Brasil',
    'Rua das Cerejeiras, 234',
    'Curitiba',
    'PR',
    7654,
    NULL,
    'Sorvetes artesanais com ingredientes naturais.',
    (SELECT id FROM categories WHERE name = 'bares'),
    -25.4284,
    -49.2733,
    'APPROVED',
    (SELECT id FROM users WHERE user_role = 'ADMIN' LIMIT 1),
    (SELECT id FROM users WHERE user_role = 'ADMIN' LIMIT 1)
),
(
    'Padaria Pão & Tradição',
    'Brasil',
    'Av. das Rosas, 789',
    'Porto Alegre',
    'RS',
    3421,
    NULL,
    'Pães e doces fresquinhos todos os dias.',
    (SELECT id FROM categories WHERE name = 'bares'),
    -30.0346,
    -51.2177,
    'APPROVED',
    (SELECT id FROM users WHERE user_role = 'ADMIN' LIMIT 1),
    (SELECT id FROM users WHERE user_role = 'ADMIN' LIMIT 1)
),
(
    'Churrascaria Gaúcha',
    'Brasil',
    'Rua dos Pampas, 456',
    'Porto Alegre',
    'RS',
    8765,
    NULL,
    'Tradicional churrasco gaúcho com cortes nobres.',
    (SELECT id FROM categories WHERE name = 'bares'),
    -30.0405,
    -51.2148,
    'APPROVED',
    (SELECT id FROM users WHERE user_role = 'ADMIN' LIMIT 1),
    (SELECT id FROM users WHERE user_role = 'ADMIN' LIMIT 1)
),
(
    'Cantina Italiana La Pasta',
    'Brasil',
    'Rua Itália, 654',
    'Florianópolis',
    'SC',
    2345,
    NULL,
    'Massas frescas e molhos caseiros.',
    (SELECT id FROM categories WHERE name = 'restaurantes'),
    -27.5954,
    -48.5480,
    'APPROVED',
    (SELECT id FROM users WHERE user_role = 'ADMIN' LIMIT 1),
    (SELECT id FROM users WHERE user_role = 'ADMIN' LIMIT 1)
),
(
    'Doceria Doce Encanto',
    'Brasil',
    'Rua das Rosas, 876',
    'Fortaleza',
    'CE',
    1122,
    NULL,
    'Doces finos e bolos personalizados.',
    (SELECT id FROM categories WHERE name = 'bares'),
    -3.7319,
    -38.5267,
    'APPROVED',
    (SELECT id FROM users WHERE user_role = 'ADMIN' LIMIT 1),
    (SELECT id FROM users WHERE user_role = 'ADMIN' LIMIT 1)
),
(
    'Bar e Petiscaria Maré Alta',
    'Brasil',
    'Av. Beira Mar, 321',
    'Recife',
    'PE',
    9090,
    NULL,
    'Petiscos e drinks à beira-mar.',
    (SELECT id FROM categories WHERE name = 'bares'),
    -8.0476,
    -34.8770,
    'APPROVED',
    (SELECT id FROM users WHERE user_role = 'ADMIN' LIMIT 1),
    (SELECT id FROM users WHERE user_role = 'ADMIN' LIMIT 1)
),
(
    'Restaurante Vegano Vida Verde',
    'Brasil',
    'Rua das Árvores, 999',
    'Brasília',
    'DF',
    1233,
    NULL,
    'Pratos veganos saborosos e saudáveis.',
    (SELECT id FROM categories WHERE name = 'restaurantes'),
    -15.8267,
    -47.9218,
    'APPROVED',
    (SELECT id FROM users WHERE user_role = 'ADMIN' LIMIT 1),
    (SELECT id FROM users WHERE user_role = 'ADMIN' LIMIT 1)
),
(
    'Café Colonial Delícias da Serra',
    'Brasil',
    'Estrada da Montanha, 777',
    'Gramado',
    'RS',
    8888,
    NULL,
    'Café colonial completo com produtos artesanais.',
    (SELECT id FROM categories WHERE name = 'restaurantes'),
    -29.3786,
    -50.8730,
    'APPROVED',
    (SELECT id FROM users WHERE user_role = 'ADMIN' LIMIT 1),
    (SELECT id FROM users WHERE user_role = 'ADMIN' LIMIT 1)
),
(
    'Pastelaria do Zé',
    'Brasil',
    'Rua Principal, 123',
    'Salvador',
    'BA',
    5555,
    NULL,
    'Pastéis crocantes e recheios variados.',
    (SELECT id FROM categories WHERE name = 'restaurantes'),
    -12.9714,
    -38.5014,
    'APPROVED',
    (SELECT id FROM users WHERE user_role = 'ADMIN' LIMIT 1),
    (SELECT id FROM users WHERE user_role = 'ADMIN' LIMIT 1)
),
(
    'Espetaria Sabor do Churrasco',
    'Brasil',
    'Av. Central, 999',
    'Goiânia',
    'GO',
    6767,
    NULL,
    'Espetos saborosos e acompanhamentos especiais.',
    (SELECT id FROM categories WHERE name = 'restaurantes'),
    -16.6869,
    -49.2648,
    'APPROVED',
    (SELECT id FROM users WHERE user_role = 'ADMIN' LIMIT 1),
    (SELECT id FROM users WHERE user_role = 'ADMIN' LIMIT 1)
);

